export const GET_USERS_SEARCH_SUCCESS = "GET_USERS_SEARCH_SUCCESS";
export const GET_USERS_SEARCH_FAILURE = "GET_USERS_SEARCH_FAILURE";
export const GET_USERS_SHOW_SUCCESS = "GET_USERS_SHOW_SUCCESS";
export const GET_USERS_SHOW_FAILURE = "GET_USERS_SHOW_FAILURE";
export const DESTROY_SESSION = "DESTROY_SESSION";